name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      # 프로젝트 실제 경로인 eclipse-workspace/SBSsw 를 정확히 지정함
      run: mvn -B package --file eclipse-workspace/SBSsw/pom.xml
